"""empty message

Revision ID: 325a6e0dbc9e
Revises: 
Create Date: 2025-03-26 16:22:39.261021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325a6e0dbc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.String(length=80), nullable=False),
    sa.Column('date_completed', sa.String(length=80), nullable=True),
    sa.Column('deadline', sa.String(length=80), nullable=True),
    sa.Column('is_completed_employer', sa.Boolean(), nullable=True),
    sa.Column('is_completed_employee', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('fk_job_poster', sa.Integer(), nullable=False),
    sa.Column('fk_job_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_job_poster'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_job_taken'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_report_reporter', sa.Integer(), nullable=False),
    sa.Column('fk_report_reported', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_report_reported'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_report_reporter'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('fk_review_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_review_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=80), nullable=False),
    sa.Column('date_paid', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('fk_transaction_sender', sa.Integer(), nullable=False),
    sa.Column('fk_transaction_receiver', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_transaction_receiver'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_transaction_sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('review')
    op.drop_table('report')
    op.drop_table('job')
    op.drop_table('user')
    # ### end Alembic commands ###
