"""empty message

Revision ID: 380e745673fe
Revises: 
Create Date: 2025-03-26 13:54:50.097264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380e745673fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed_employer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_completed_employee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('taken_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['poster_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['taken_id'], ['id'])
        batch_op.drop_column('is_completed')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('taken_id')
        batch_op.drop_column('poster_id')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('is_completed_employee')
        batch_op.drop_column('is_completed_employer')

    # ### end Alembic commands ###
